<?php

namespace app\models;

use app\traits\Morphed;
use Exception;
use function file_exists;
use Yii;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "images".
 *
 * @property int $id
 * @property string $name
 * @property int $size
 * @property int $object_id
 * @property string $object_type
 */
class Image extends ActiveRecord
{
    const SMALL = 'small';
    const MEDIUM = 'medium';
    const LARGE = 'large';
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'images';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['object_id'], 'integer'],
            [['size'], 'string'],
            [['name', 'object_type'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'Идентификатор',
            'name' => 'Название',
            'size' => 'Размер',
            'object_id' => 'Идентификатор объекта',
            'object_type' => 'Тип объекта',
        ];
    }

    public function beforeDelete()
    {
        $this->deleteFile();
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    protected function deleteFile()
    {
        $path = Yii::getAlias('@web') . 'uploads/' . $this->object_type . '/' . $this->object_id . '/thumbs/' . $this->name;
        if (file_exists($path)) {
            unlink($path);
        }
    }

}
